name: pyda_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiobotocore=0.10.0=py_0
  - aiohttp=3.9.3=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arm_pyart=1.18.3=py311h459d7ec_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.1.0=py311h06a4308_0
  - blas=1.0=openblas
  - blosc=1.21.5=h0f2a231_0
  - bokeh=2.4.3=py311h06a4308_0
  - boost-cpp=1.78.0=h5adbc97_2
  - botocore=1.10.58=py_0
  - branca=0.6.0=py311h06a4308_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py311hb755f60_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.27.0=hd590300_0
  - ca-certificates=2024.9.24=h06a4308_0
  - cached-property=1.5.2=py_0
  - cairo=1.16.0=ha61ee94_1014
  - cartopy=0.22.0=py311h320fe9a_1
  - certifi=2024.8.30=py311h06a4308_0
  - cfitsio=4.2.0=hd9d235c_0
  - cftime=1.6.2=py311hbed6279_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=py311h06a4308_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - cloudpickle=2.2.1=py311h06a4308_0
  - cmweather=0.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.0=py311h9547e67_0
  - curl=8.1.2=h409715c_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.2=py311h5eee18b_0
  - dask=2023.3.0=pyhd8ed1ab_0
  - dask-core=2023.3.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2023.3.0=pyhd8ed1ab_0
  - docutils=0.18.1=py311h06a4308_3
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - fiona=1.9.5=py311ha02d727_0
  - folium=0.14.0=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.50.0=py311h459d7ec_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h267a509_2
  - freexl=1.0.6=h166bdaf_1
  - frozenlist=1.4.0=py311h5eee18b_0
  - fsspec=2023.10.0=py311h06a4308_0
  - g2clib=1.6.0=3
  - gdal=3.6.2=py311hadb6153_9
  - geographiclib=2.0=py311h06a4308_0
  - geopandas=0.14.4=pyhd8ed1ab_0
  - geopandas-base=0.14.4=pyha770c72_0
  - geopy=2.4.1=pyhd8ed1ab_1
  - geos=3.11.1=h27087fc_0
  - geotiff=1.7.1=h7a142b4_6
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - h5netcdf=1.2.0=py311h06a4308_0
  - h5py=3.8.0=nompi_py311h1db17ec_100
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - hdfeos2=2.20=hb955811_1002
  - hdfeos5=5.1.16=hc55c121_12
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icu=70.1=h27087fc_0
  - idna=3.6=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipython=8.22.2=pyh707e725_0
  - jasper=2.0.33=h0ff4b12_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py311h06a4308_0
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.2.0=py311h06a4308_0
  - jpeg=9e=h0b41bf4_3
  - json-c=0.16=hc379101_0
  - kealib=1.5.0=ha7026e8_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py311h9547e67_1
  - krb5=1.20.1=h81ceb04_0
  - lat_lon_parser=1.3.0=pyhd8ed1ab_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=21_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=21_linux64_openblas
  - libcurl=8.1.2=h409715c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgdal=3.6.2=h6c674c2_9
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.1=hebfc3b9_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - libkml=1.3.0=h01aab08_1016
  - liblapack=3.9.0=21_linux64_openblas
  - libnetcdf=4.9.1=nompi_h34a3ff0_101
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libpq=15.2=hb675445_0
  - librttopo=1.1.0=ha49c73b_12
  - libspatialindex=1.9.3=h2531618_0
  - libspatialite=5.0.1=h221c8f1_23
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=hca2bb57_4
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - locket=1.0.0=py311h06a4308_0
  - lz4=4.3.2=py311h5eee18b_0
  - lz4-c=1.9.4=hcb278e6_0
  - mapclassify=2.5.0=py311h06a4308_0
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib-base=3.8.3=py311h54ef318_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_0
  - metpy=1.6.1=pyhd8ed1ab_0
  - msgpack-python=1.0.3=py311hdb19cb5_0
  - multidict=6.0.4=py311h5eee18b_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4.20240210=h59595ed_0
  - netcdf4=1.6.3=nompi_py311ha396515_100
  - networkx=3.3=py311h06a4308_0
  - nspr=4.35=h27087fc_0
  - nss=3.98=h1d7d5a4_0
  - numpy=1.26.4=py311h24aa872_0
  - numpy-base=1.26.4=py311hbfb1bba_0
  - open-radar-data=0.1.0=pyhd8ed1ab_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.5=hd590300_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.1=py311h320fe9a_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.1=py311h06a4308_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py311h50def17_1
  - pint=0.23=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - pooch=1.8.1=pyhd8ed1ab_0
  - poppler=23.03.0=h091648b_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.2=h3248436_0
  - proj=9.1.1=h8ffa02c_2
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.0=py311h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pynio=1.5.5=py311h5956141_22
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyproj=3.5.0=py311h945b3ca_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.1.1=pyhd8ed1ab_0
  - python=3.11.6=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-lmdb=1.4.1=py311h6a678d5_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rtree=1.0.1=py311h06a4308_0
  - s3fs=0.6.0=pyhd3eb1b0_0
  - scikit-learn=1.2.2=py311h6a678d5_1
  - scipy=1.12.0=py311h64a7726_2
  - seaborn=0.12.2=py311h06a4308_0
  - setuptools=69.2.0=pyhd8ed1ab_0
  - setuptools-scm=8.0.4=py311h06a4308_0
  - setuptools_scm=8.0.4=hd3eb1b0_0
  - shapely=2.0.1=py311h0f577a2_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.45.2=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tiledb=2.13.2=hd532e3d_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=py311h06a4308_0
  - tornado=6.3.3=py311h5eee18b_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzcode=2024a=h3f72095_0
  - tzdata=2024a=h0c530f3_0
  - uriparser=0.9.7=h59595ed_1
  - urllib3=2.2.1=pyhd8ed1ab_0
  - versioneer=0.29=py311h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_0
  - wrapt=1.14.1=py311h5eee18b_0
  - xarray=2024.2.0=pyhd8ed1ab_0
  - xarray-datatree=0.0.14=pyhd8ed1ab_0
  - xerces-c=3.2.4=h55805fa_1
  - xmltodict=0.13.0=py311h06a4308_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xradar=0.5.0=pyhd8ed1ab_0
  - xyzservices=2022.9.0=py311h06a4308_1
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py311h5eee18b_0
  - zict=3.0.0=py311h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
prefix: /mnt/lfs5/BMC/wrfruc/murdzek/conda/env/my_py
